### ISSUE TITLE
Google auth did not work with any hostedDomain

### ISSUE THREAD

**Issue by jquiros2** [LayeredStudio/quick-login#9]
Kept getting "not a member of '' domain then tried adding a '*' for hosted domain, and got the same error.

Finally commented this in /quick-login/src/Provider/Google.php

/**                     'hostedDomain'                          =>      $this->getOption('hostedDomain', 'gmail.com'),  */

To get it to work.  Thank YOU by the way!

**Comment by AndreiIgna** [comment]
Hi,

Thanks for reporting this. It looks strange that "gmail.com" is referred there, that would indeed cause some issues. I'm checking now the plugin and see what causes this.

**Comment by jquiros2** [comment]
I left that in from my testing-  strange I couldn’t get it to work with the default '*' or ''  either.  If it works for others it’s ok... Will try to track down more when I get a chance.  Thank you!

**Comment by jquiros2** [comment]
Tried again uncommenting ln72 ... with the field blank in options, get "Google - User is not part of domain '*'"  It works really really well, though (and so does "if-menu") so again, thank you.

**Comment by AndreiIgna** [comment]
This is now resolved in the latest plugin version. That line of code was causing the issues when not filling a custom domain.

Now the plugin does a better check before setting that option, and Google login should work fine for both regular accounts and G Suite domains.
